### ISSUE TITLE
Lack of logs reported in pipeline

### ISSUE THREAD

**Issue by Petronian** [Petronian/demayo-bulk-omics#1]
No logs from any tools (`fastqc`, `hisat2`, etc.) are reported during the pipeline's run. Needs to be fixed or add a tunable parameter.

**Comment by Petronian** [comment]
This includes `-annStats` option from HOMER.

**Comment by rmarquaad** [comment]
I would especially appreciate the alignment log from hisat2 in order to determine how well the reads aligned to the reference genome.

**Comment by Petronian** [comment]
@rmarquaad HISAT2 alignment logs are among the things I implemented; see the linked PR (pull request) above for details about what specifically changed. Report bugs as they arise!
